
name: day Python Script

on:
  schedule:
    - cron: '32 6 * * *'  
    # 每天 6 点执行
    # - cron: '*/5 * * * *'  
    # 每5分钟执行一次

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Set Beijing Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python ./day.py
# python ./validation-dashboard/json2htmlrunner.py